version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: .
    env_file:
      - django.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - db
    command: ./bin/run_dev

volumes:
  pgdata:
