# Generated by Django 3.0.5 on 2020-04-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200416_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='source',
            field=models.TextField(blank=True, help_text='Where was this content imported from?'),
        ),
    ]
