# Generated by Django 3.0.5 on 2020-04-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200416_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='publish_to_icontact',
            field=models.BooleanField(default=False),
        ),
    ]
