# Generated by Django 3.0.5 on 2020-04-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newspage_publish_to_icontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='publish_to_icontact',
            field=models.BooleanField(default=False, help_text='If checked, a draft message will be created on iContact the next time this page is published'),
        ),
    ]
