# Generated by Django 3.0.5 on 2020-04-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200417_0811'),
        ('news', '0010_newspage_source'),
    ]

    operations = [
    ]
