# Generated by Django 3.2.4 on 2021-07-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_merge_20200417_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='publish_to_icontact',
        ),
    ]
