from .base import *

DEBUG = False
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")

try:
    from .local import *
except ImportError:
    pass

WAGTAILCONTENTIMPORT_MICROSOFT_CLIENT_ID = os.getenv('WAGTAILCONTENTIMPORT_MICROSOFT_CLIENT_ID', '')
