# Generated by Django 3.2.4 on 2021-07-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icontact', '0003_auto_20200417_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
